server {
    listen 80;
    listen [::]:80;


    server_name _;

    location / {
        # 80번 포트로 들어온 요청을 내부의 3000번 포트(Bun/Express)로 전달
        proxy_pass http://localhost:3000;

        # 리버스 프록시를 위한 필수 헤더 설정
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        # 실제 클라이언트 IP를 백엔드 서버에 전달
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}